language: julia
julia:
  - 0.6
notifications:
  email: false
testscript:
  julia -e 'Pkg.build("HWintegration")'
if [ -f test/runtests.jl ]; then
  julia --check-bounds=yes -e 'Pkg.test("HWintegration", coverage=true)'
fi
#script: # the default script is equivalent to the following
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("Example"); Pkg.test("Example"; coverage=true)';
